theme: jekyll-theme-minimal
title: Tim Williams
image: assets/images/TWHeadshot.png
description: Linked Data & Knowledge Graph enthusiast, practitioner, and educator. Over fifteen years of experience in the pharmaceutical industry and a previous ten in healthcare and environmental informatics.
